### ISSUE TITLE
Error 503: Service Unavailable

### ISSUE THREAD

**Issue by Moire9** [Rayrsn/Curseforge-Modpack-Downloader#1]
You may be using an outdated API version; when trying to download the files the curse endpoint returns 503.
```
Downloading manifest
202 Mods
Traceback (most recent call last):
  File "/home/sir/work/test/Curseforge-Modpack-Downloader/main.py", line 30, in <module>
    mod_json = json.loads((urllib.request.urlopen("https://addons-ecs.forgesvc.net/api/v2/addon/{}/files".format(projectID))).read().decode())
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
```

**Comment by Rayrsn** [comment]
Hi, CurseForge have deprecated the private api i was using in place of a [new one](https://docs.curseforge.com) that requires a token.
Unfortunately I no longer have the motivation to maintain this project, You are more than welcome to create a pull request if you want to fix/change the code.

**Comment by Moire9** [comment]
That's what I assumed. Perhaps mark the repository as archived?

**Comment by Rayrsn** [comment]
I updated the code for the new API
